name: "${project.name}"
main: no.atc.floyd.bukkit.kit.KitPlugin
version: "${project.version}"
website: "${project.url}"
author: FloydATC
description: "${project.description}"

commands:
  kit:
    description: Show a list of kit names or get a named kit
    usage: /<command> [<kit>] [<players>]
